"""sprint_2_5_extend_quiz_models

Revision ID: 2463fd29b9fe
Revises: f8b91a23c456
Create Date: 2026-07-25 13:45:02.853130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2463fd29b9fe'
down_revision: Union[str, None] = 'f8b91a23c456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_problems_id', table_name='problems')
    op.add_column('quiz_questions', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('quiz_questions', sa.Column('concept', sa.String(), nullable=True))
    op.add_column('quiz_questions', sa.Column('expected_time_seconds', sa.Integer(), nullable=True))
    op.add_column('quiz_questions', sa.Column('hints', sa.JSON(), nullable=True))
    op.add_column('quiz_questions', sa.Column('option_explanations', sa.JSON(), nullable=True))
    op.add_column('quizzes', sa.Column('xp_reward', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('pass_mark', sa.Integer(), nullable=True))
    op.add_column('quizzes', sa.Column('question_count', sa.Integer(), nullable=True))
    op.add_column('user_quiz_attempts', sa.Column('xp_earned', sa.Integer(), nullable=True))
    op.add_column('user_quiz_attempts', sa.Column('bonus_xp', sa.Integer(), nullable=True))
    op.add_column('user_quiz_attempts', sa.Column('flagged_questions', sa.JSON(), nullable=True))
    op.add_column('user_quiz_attempts', sa.Column('skipped_questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_quiz_attempts', 'skipped_questions')
    op.drop_column('user_quiz_attempts', 'flagged_questions')
    op.drop_column('user_quiz_attempts', 'bonus_xp')
    op.drop_column('user_quiz_attempts', 'xp_earned')
    op.drop_column('quizzes', 'question_count')
    op.drop_column('quizzes', 'pass_mark')
    op.drop_column('quizzes', 'xp_reward')
    op.drop_column('quiz_questions', 'option_explanations')
    op.drop_column('quiz_questions', 'hints')
    op.drop_column('quiz_questions', 'expected_time_seconds')
    op.drop_column('quiz_questions', 'concept')
    op.drop_column('quiz_questions', 'tags')
    op.create_index('ix_problems_id', 'problems', ['id'], unique=False)
    # ### end Alembic commands ###
