"""Add_Learning_Engine_models

Revision ID: a8e0cfc86299
Revises: 
Create Date: 2026-07-20 02:11:13.194600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e0cfc86299'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('study_duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index(op.f('ix_daily_activities_id'), 'daily_activities', ['id'], unique=False)
    op.create_table('user_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('mission_type', sa.String(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_missions_id'), 'user_missions', ['id'], unique=False)
    op.create_table('revision_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_tasks_id'), 'revision_tasks', ['id'], unique=False)
    op.add_column('user_progress', sa.Column('solving_time_seconds', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('revision_stage', sa.Integer(), nullable=True))
    op.add_column('user_topic_progress', sa.Column('video_watched', sa.Boolean(), nullable=True))
    op.add_column('user_topic_progress', sa.Column('notes_read', sa.Boolean(), nullable=True))
    op.add_column('user_topic_progress', sa.Column('quiz_completed', sa.Boolean(), nullable=True))
    op.add_column('user_topic_progress', sa.Column('boss_battle_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_topic_progress', 'boss_battle_completed')
    op.drop_column('user_topic_progress', 'quiz_completed')
    op.drop_column('user_topic_progress', 'notes_read')
    op.drop_column('user_topic_progress', 'video_watched')
    op.drop_column('user_progress', 'revision_stage')
    op.drop_column('user_progress', 'solving_time_seconds')
    op.drop_index(op.f('ix_revision_tasks_id'), table_name='revision_tasks')
    op.drop_table('revision_tasks')
    op.drop_index(op.f('ix_user_missions_id'), table_name='user_missions')
    op.drop_table('user_missions')
    op.drop_index(op.f('ix_daily_activities_id'), table_name='daily_activities')
    op.drop_table('daily_activities')
    # ### end Alembic commands ###
